appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: dFGpjWAbBmkNF+rdcqJWbeFDe/LF9qCi4qlu/7rBW4Ex0wgEuQc+kU17z5VtaZGUC+E6aCj7e1vqJIqLdb+3/QoYEMNeH9B8/ZHvJ4edIe+NqmwOmL6H4mC4iZzhwxkSxxMU6E3OscPAWKEo+wcNnRLYb0ogbYeQAiAKpKboMPa1uCdYcZotyKy7MBi091Vudxmr2kI2qwWc8AFWR2w6n8pBzKn07yuxaMx31rVxYASNs9Qncg5DYtrHm69TDWqMlway+qlCTzkkzyzcyRTb6QNsNlcUT9+lDK0vOje7AMzqPtOL+rgLKcOLBrMml4vRW7O/JcfQYrDf+8ij3q/KyvO4EwzYuiT3sGboGNBtuM63LIp1bxA9QpOr5SIT6RZRSvQbS6m6dXCZgW6y/4ccDJqIFxX5kHWbGM8KNYrjJNoec9VGo9ufZF/Bkwb8+H6Pwoe0xg7Fjtese4g86RfxXSmZ2bntruO8BK0GfDDjPZ23tkAg7gAZ3ocEtG83CSqB84Bz5Rk2DHopHfK+KDLtoWOB6r8Dnzk97phztvm1tnJvB4iqFpTTqF8tAkz6adVN7TeoH/T8nlpbHI+dE9K44g1AhTRm6lG5kNme/rvFMoIdlhwt8+qpTjOJPTRKeYBmgfpk00EHDR1BR8XK6u0s2I0keLDYU7xoAodHWtTLW10=
conda_forge_output_validation: true
